# Generated by Django 4.2.2 on 2024-11-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderProducts',
        ),
    ]
